In [1]:
%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = 'retina'

In [2]:
import numpy as np
from scipy import integrate

from rbergomi import RoughBergomi

In [10]:
params = {
    "s0": 1.0,
    "xi0": lambda u: np.ones_like(u) * 0.235**2,
    "rho": -0.7,
    "H": 0.1,
    "eta": 1.2,
}
# params["eta"] = 1.3 * np.sqrt(2.0 * params["H"])
print(params)

rbergomi = RoughBergomi(**params)

{'s0': 1.0, 'xi0': <function <lambda> at 0x1101cce00>, 'rho': -0.7, 'H': 0.1, 'eta': 1.2}


In [11]:
# TODO:
# fix coefficients and tests (gamma1, gamma2, gamma3)
# generate vix paths

In [72]:
T = 1.2
n_disc = 300
n_mc = 10**5

k = np.linspace(-0.1, 0.1, 11)
rbergomi.implied_vol_vix(k=k, T=T, n_disc=n_disc, n_mc=n_mc)

array([0.39756536, 0.39762735, 0.39772749, 0.39785624, 0.39798975,
       0.39811373, 0.39821863, 0.39833307, 0.39845705, 0.39857149,
       0.39866686])

In [80]:
rbergomi.implied_vol_vix_approx(T=T, k=k, order=3)

array([0.39555788, 0.39573431, 0.39590597, 0.3960824 , 0.39625406,
       0.39643049, 0.39660215, 0.39677858, 0.39695024, 0.39712667,
       0.39729834])

In [96]:
T = 1.0 / 12.0
vix_fut_mc = 100 * rbergomi.price_vix_fut(T=T, n_disc=n_disc, n_mc=n_mc, rule="trap")

In [97]:
vix_fut_approx = 100.0 * rbergomi.price_vix_fut_approx(T=T, order=3)

In [98]:
print(f"VIX future MC: {vix_fut_mc:.4f}")
print(f"VIX future approx: {vix_fut_approx:.4f}")

VIX future MC: 22.9028
VIX future approx: 22.8972


In [92]:
rbergomi.price_vix(k=0.0, T=T, n_disc=n_disc, n_mc=n_mc, rule="left")

array([0.03681637])

In [70]:
order = 3
rbergomi.price_vix_approx(
    K=rbergomi.price_vix_fut_approx(T=T, order=order), T=T, order=order
)

np.float64(0.020555203823353435)

In [71]:
k = [-0.05, 0.0, 0.05]
k = np.atleast_1d(np.asarray(k))
F = rbergomi.price_vix_fut_approx(T=T, order=3)
K = F * np.exp(k)

rbergomi.implied_vol_vix_approx(T=T, k=0.0)

array([0.7811451])

In [ ]:
T = 0.8


print(rbergomi.mean_proxy(T, quad_scipy=True))
print(rbergomi.mean_proxy_flat(T))

-0.33144981698477705
-0.33144981698477993


In [15]:
print(rbergomi.var_proxy(T, quad_scipy=True))
print(rbergomi.var_proxy_flat(T))

0.6530213939464953
0.6530213939471478


In [89]:
print(rbergomi.gamma_1_proxy(T, n_quad=80))
print(rbergomi.gamma_1_proxy_flat(T))

0.006647646313948319
0.00667600218698899


In [85]:
print(rbergomi.gamma_2_proxy(T, n_quad=80))
print(rbergomi.gamma_2_proxy_flat(T, quad_scipy=False, n_quad=80))
print(rbergomi.gamma_2_proxy_flat(T, quad_scipy=True))

-0.0030691394044134734
-0.003070088319012787
-0.003073745696086594


In [91]:
print(rbergomi.gamma_3_proxy(T, n_quad=80))
print(rbergomi.gamma_3_proxy_flat(T, quad_scipy=False, n_quad=80))
print(rbergomi.gamma_3_proxy_flat(T, quad_scipy=True))

0.001388674194143182
0.0013869274255390862
0.0013891498337460506
